
[functions.vectorize-knowledge-base]
enabled = true
verify_jwt = true
import_map = "./functions/vectorize-knowledge-base/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/vectorize-knowledge-base/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/vectorize-knowledge-base/*.html" ]
